server:
  port: 9001
  servlet:
    context-path: /shopdev

jdbc:
  url: jdbc:mysql://localhost:3306/shopdev?useUnicode=true&characterEncoding=utf8&useSSL=false
  driver: com.mysql.jdbc.Driver
  username: root
  pwd: root

mybatis:
  mybatis_config_file: classpath:mybatis-config.xml
  entity_package: com.cxy.demo.bean
  mapper-locations: /orm/**.xml