(function(z){
var UU=function(a){z.Q.apply(this,arguments)};var VU=function(a,b){return a.uc.Tn.find('input[name\x3d"'+b+'"]')};
var WU=function(a,b){var c=a.uc,d=(0,window.$)(b.target),f=d.attr("name"),g=d.parents(".ImageUploader"),h=(0,window.$)(".ImageUploader-tip",g),f=a.getFile(f),k=g.data("max-size");f?(h.text(h.text().replace("涓婁紶","淇敼")),k&&f.size>k?c.$i(g,{Ka:"鏂囦欢澶у皬涓嶈兘瓒呰繃 "+k/1024/1024+" mb"}):(c.gF(g),a.upload(f).done(function(a){a=void 0===a?{}:a;if(1===a.code)return c.$i(g,{Ka:"涓婁紶澶辫触锛岃閲嶈瘯 \x3e_\x3c"});a=a.msg;a[0]=a[0].replace("_b","");d.data("file",{raw_width:a[1],raw_height:a[2],token:a[3]});g.removeClass("is-error");
c.Tf(g,a)}).fail(function(){c.$i(g,{Ka:"涓婁紶澶辫触锛岃閲嶈瘯 \x3e_\x3c"})}))):h.text(h.text().replace("淇敼","涓婁紶"))};var XU=function(a,b){b.on("change",function(b){WU(a,b)})};var YU=function(a){a.on("click",function(a){a=(0,window.$)(a.target).parents(".ImageUploader").find(".ImageUploader-image");if(a.data("original"))return a.click(),!1})};
var ZU=function(a){var b={};(0,window.$)(".ImageUploader-uploadButton",a.uc.Tn).each(function(a,d){var f=(0,window.$)(d),g=f.attr("name");(f=f.data("file"))&&(b[g]={raw_width:f.raw_width,raw_height:f.raw_height,token:f.token})});return b};var $U=function(a){z.Q.apply(this,arguments)};
var aV=function(a){for(var b=new z.oA,c=z.ha([{value:"change-phone",label:"鍙樻洿鎵嬫満鍙�"},{value:"change-manager",label:"鍙樻洿璐熻矗浜�"}]),d=c.next();!d.done;d=c.next())d=d.value,d=new z.jA(d.label,d),b.Ha(d);var f=(0,window.$)(".ManagerField .edit"),g=(0,window.$)(".MoreSettings"),c=new z.vA("change",b);c.Rb=z.Hl;c.w(f[0]);z.Ac(c,a);a.o().g(b,"action",function(a){var b=a.target.X(),c=g.filter(function(){return(0,window.$)(this).hasClass(b.value)});g.not(c).slideUp(function(){c.slideDown()});f.blur()})};
var bV=function(){var a=(0,window.$)("form.ChangeAvatarForm");if(0!==a.length){var b=new UU;b.init({Tn:(0,window.$)(".ImageUploader",a),gF:function(a){a.parents(".SettingItem-content").find(".SettingItem-error").remove()},Tf:function(a,b){(0,window.$)(".ImageUploader-image",a).attr({src:b[0],"data-original":b[0],"data-rawwidth":b[1],"data-rawheight":b[2]})},$i:function(a,b){var c=a.parents(".SettingItem-content");c.find(".SettingItem-error").remove();c.append('\x3cp class\x3d"SettingItem-error"\x3e'+
b.Ka+"\x3c/p\x3e")}});var c=function(){var c=a.jc(),d=ZU(b);return Object.assign(c,d)};a.on("click",".MoreSettings-submit",function(){a.find(".SettingItem-error").remove();window.$.ajax({type:"POST",url:"/settings/account/org_update_avatar",data:JSON.stringify(c()),contentType:"application/json"}).done(function(b){if(b&&b.r){b=b.msg;for(var c="",d=z.ha(Object.keys(b)),f=d.next();!f.done;f=d.next())c=f=f.value,a.find("*[name\x3d"+f+"]").parents(".SettingItem-content").append('\x3cp class\x3d"SettingItem-error"\x3e'+
b[f]+"\x3c/p\x3e");window.location.hash=c}else window.sessionStorage.setItem("settings/org_profile:pageAlert","澶村儚鍙樻洿鐢宠宸叉彁浜�"),window.location.reload()}).fail(function(){a.append('\x3cp class\x3d"SettingItem-error SettingItem--noneLabel"\x3e澶村儚鍙樻洿鐢宠鎻愪氦澶辫触锛岃閲嶈瘯 \x3e_\x3c\x3c/p\x3e')})});a.on("click",".MoreSettings-cancel",function(){a.find(".SettingItem-error").remove()});var d=function(a){var c=VU(b,a),d=c.data("original");d?(c.parents(".ImageUploader").find(".ImageUploader-image").attr("src",d.original),
c.data("file",d)):(a=VU(b,a),c=a.parents(".ImageUploader"),d=a.clone().val(""),XU(b,d),a.replaceWith(d),c.find(".ImageUploader-image").removeAttr("src").data({original:""}),a=c.find(".ImageUploader-tip"),c=a.text(),a.text(c.replace("淇敼","涓婁紶")))},f=function(){a.find(".SettingItem-error").remove();var b=(0,window.$)(".SettingItem-row.AvatarProxyAuthCertEditor");"2"===(0,window.$)('input[name\x3d"is_org_name_match_with_cert"]:checked').val()?b.slideDown():b.slideUp(function(){d("avatar_proxy_auth_cert")})},
g=function(){a.find(".SettingItem-error").remove();var b=(0,window.$)(".SettingItem.IsOrgNameMatchWithCertRadioGroup"),c=(0,window.$)(".SettingItem-row.AvatarTrademarkCertEditor"),f=(0,window.$)(".SettingItem-row.AvatarGuaranteeCertEditor");"1"===(0,window.$)('select[name\x3d"is_avatar_contains_trademark"]').val()?(c.show(),f.hide(),d("avatar_trademark_cert"),b.slideDown()):(c.hide(),f.show(),d("avatar_guarantee_cert"),b.slideUp(function(){d("avatar_proxy_auth_cert")}))};f();g();(0,window.$)('input[name\x3d"is_org_name_match_with_cert"]').on("change",
f);(0,window.$)('select[name\x3d"is_avatar_contains_trademark"]').on("change",g);var f=(0,window.$)(".ProfileAvatarEditor",a),h=(0,window.$)('input[name\x3d"avatar_path"]',a);(new z.$z({SI:!0,Tf:function(a){h.val(a.id)}})).w(f.get(0));var k=(0,window.$)(".SettingItem-hideForChangeAvatar");a.on("click",".MoreSettings-cancel",function(){k.slideDown();a.slideUp()});(0,window.$)(".AvatarField .edit").on("click",function(){(0,window.$)(".MoreSettings").not(a).slideUp(function(){k.slideUp();a.slideDown()})})}};
var cV=function(){(new z.nz).init({va:(0,window.$)("form.change-phone"),Nm:"SettingItem",nt:dV,co:function(){window.sessionStorage.setItem("settings/org_profile:pageAlert","鎵嬫満鍙峰彉鏇存垚鍔�");window.location.reload()}})};
var eV=function(){(new z.nz).init({va:(0,window.$)("form.change-manager"),Nm:"SettingItem",nt:dV,Bx:function(){return new window.Promise(function(a,b){z.W.alert({title:"璐熻矗浜哄彉鏇�",modal:!0,content:(0,window.$)("#change-confirmation").html(),buttons:{yes:"纭鎻愪氦"}},function(c){c?a():b()})})},co:function(){window.sessionStorage.setItem("settings/org_profile:pageAlert","璐熻矗浜哄彉鏇磋姹傚凡鎻愪氦");window.location.reload()}})};var fV=function(a){z.Q.apply(this,arguments)};var gV=function(a){z.Q.apply(this,arguments)};
window.$.fn.FZ=function(){this.each(function(){var a=(0,window.$)(this),b=a.find(".Uploader-label"),c=a.find('input[type\x3d"file"]'),d=a.data("max-size");c.on("change",function(){var a=(0,window.$)(this).get(0).files[0];d&&a.size>d?b.addClass("is-error").text("瑕佷笂浼犳枃浠惰秴杩囬檺鍒跺ぇ灏�"):(a=a.name||a.fileName,b.removeClass("is-error").text(a))})})};z.n(UU,z.Q);UU.prototype.init=function(a){a=void 0===a?{}:a;this.uc=Object.assign({Tn:(0,window.$)(".ImageUploader"),ll:z.um.Kn+"/upload",gF:window.$.noop,Tf:window.$.noop,$i:window.$.noop},a);XU(this,this.uc.Tn.find('input[type\x3d"file"]'));YU(this.uc.Tn.find(".ImageUploader-zoomIn"))};UU.prototype.upload=function(a){var b=new window.FormData;b.append("via","xhr2");b.append("upload_file",a);return window.$.ajax({type:"POST",url:this.uc.ll,data:b,processData:!1,contentType:!1,xhrFields:{withCredentials:!0}})};
UU.prototype.getFile=function(a){a=VU(this,a).get(0).files;var b=null;a&&a.length&&(b=a[0]);return b};var dV=[{name:"id_card",Wn:18,Ka:"韬唤璇佸彿搴斾负 18 浣�"}];z.n($U,z.Q);$U.prototype.init=function(){var a=window.sessionStorage.getItem("settings/org_profile:pageAlert");a&&(z.nG(a),window.sessionStorage.removeItem("settings/org_profile:pageAlert"));(0,window.$)(".Uploader").FZ();this.fu();bV();cV();eV();aV(this)};
$U.prototype.fu=function(){(0,window.$)(".captcha .send").each(function(){var a=void 0,b=(0,window.$)(this),c=b.text(),d=b.parents("form"),f=d.find("[name\x3dadmin_phone_no]"),g=z.tk(b,60,function(b){return b?"楠岃瘉鐮佸凡鍙戦€佸埌 "+a+" 锛�%s 绉掑悗鍗冲彲閲嶅彂":c},function(b){b.preventDefault();a=f.val().trim();if(!a)return f.parents(".SettingItem").addClass("is-error").find(".SettingItem-error").remove().end().find(".SettingItem-content").append('\x3cp class\x3d"SettingItem-error"\x3e闇€濉啓瑕侀獙璇佺殑鎵嬫満鍙穃x3c/p\x3e'),!1;window.$.post("/settings/account/send_phone_digits",
{phone_no:a})});d.on("click",".MoreSettings-cancel",function(a){a.preventDefault();d.slideUp();g.cancel()}).on("keyup",'input[name\x3d"admin_phone_no"]',function(){g.cancel()})})};z.n(fV,z.Q);fV.prototype.init=function(){new z.lG};z.n(gV,z.Q);gV.prototype.init=function(){window.document.getElementById("react")&&z.sx("OrgOpHelp").then(function(a){return a.render()})};z.x("ZH.entryOrgSettingsProfile",function(){(new $U).init()});z.x("ZH.entryOrgSettingsQualification",function(){(new fV).init()});z.x("ZH.entryOrgOpHelp",function(){(new gV).init()});z.lg("page-org");}).call(this, __z_z__);
// # sourceURL=/static/revved/-/js/closure/page-org.5efce1a3.js
